# Generated by Django 2.1.3 on 2018-11-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sku', models.IntegerField()),
                ('description', models.TextField()),
                ('remark', models.CharField(max_length=100)),
            ],
        ),
    ]
